name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for putting an issue on FridayChatBot! We would love to see what need to be fixed!"
        pr-message: "Thanks for creating a pull request on FridayChatBot!"
